# Welcome to Beautiful Jekyll!
# This config file is meant for settings that affect your entire website. When you first
# set up your website you should go through all these settings and edit them, but after
# the initial set up you won't need to come back to this file often.

# --- Required options --- #

# Name of website
title: PandaMun's IT blog

# Your name to show in the footer
author: PandaMun

url: "https://pandamun.github.io/"


# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Category:
    - java : "/category/java"
    - security : "/category/security"
    - web : "category/web"
    - database : "category/database"
    - jpa : "category/jpa"
    - knowledge : "/category/knowledge"


# --- Logo --- #

avatar: "/assets/img/panda-icon.png"

round-avatar: true

# --- Footer options --- #
social-network-links:
  github: PandaMun

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

rss-description: This website is a virtual proof that I'm awesome

# --- General options --- #

excerpt_length: 50

feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
# post_search: false

# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"


# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/Seoul"

markdown: kramdown
highlighter: rouge

permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-paginate
  - jekyll-sitemap
